# Configuration file for the STM32 for VSCode extension
# Arrays can be inputted in two ways. One is: [entry_1, entry_2, ..., entry_final]
# or by adding an indented list below the variable name e.g.:
# VARIABLE:
# - entry_1
# - entry_2

# The project name
target: final_project
# Can be C or C++
language: C

optimization: Og

# MCU settings
targetMCU: stm32f4x
cpu: cortex-m4 # type of cpu e.g. cortex-m4
fpu: fpv4-sp-d16 # Defines how floating points are defined. Can be left empty.
floatAbi: -mfloat-abi=hard
ldscript: STM32F469NIHx_FLASH.ld # linker script

# Compiler definitions. The -D prefix for the compiler will be automatically added.
cDefinitions:
  - USE_HAL_DRIVER
  - STM32F469xx

cxxDefinitions:
  - USE_HAL_DRIVER
  - STM32F469xx

asDefinitions: []

# Compiler definition files. you can add a single files or an array of files for different definitions.
# The file is expected to have a definition each new line.
# This allows to include for example a .definition file which can be ignored in git and can contain
# This can be convenient for passing along secrets at compile time, or generating a file for per device setup.
cDefinitionsFile:
cxxDefinitionsFile:
asDefinitionsFile:

# Compiler flags
cFlags: []
cxxFlags: []
assemblyFlags: []
linkerFlags:
  - -specs=nano.specs
  - -specs=rdimon.specs
  - -u _printf_float

# libraries to be included. The -l prefix to the library will be automatically added.
libraries:
  - :libPDMFilter_CM4_GCC_wc32.a

# Library directories. Folders can be added here that contain custom libraries.
libraryDirectories:
  - Middlewares/ST/STM32_Audio/Addons/PDM/Lib

# Files or folders that will be excluded from compilation.
# Glob patterns (https://www.wikiwand.com/en/Glob_(programming)) can be used.
# Do mind that double stars are reserved in yaml
# these should be escaped with a: \ or the name should be in double quotes e.g. "**.test.**"
excludes:
  - "**/Examples/**"
  - "**/examples/**"
  - "**/Example/**"
  - "**/example/**"
  - "**_template.*"

# Include directories (directories containing .h or .hpp files)
# If a CubeMX makefile is present it will automatically include the include directories from that makefile.
includeDirectories:
  - Core/Inc
  - FATFS/Target
  - FATFS/App
  - PDM2PCM/App
  - USB_HOST/App
  - USB_HOST/Target
  - Drivers/STM32F4xx_HAL_Driver/Inc
  - Drivers/STM32F4xx_HAL_Driver/Inc/Legacy
  - Middlewares/Third_Party/FatFs/src
  - Middlewares/ST/STM32_Audio/Addons/PDM/Inc
  - Middlewares/ST/STM32_USB_Host_Library/Core/Inc
  - Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc
  - Drivers/CMSIS/Device/ST/STM32F4xx/Include
  - Drivers/CMSIS/Include
  - Inc/**
  - Core/Inc/**
  - Core/Lib/**
  - Src/**
  - Core/Src/**
  - Core/Lib/**

# Files that should be included in the compilation.
# If a CubeMX makefile is present it will automatically include the  c and cpp/cxx files from that makefile.
# Glob patterns (https://www.wikiwand.com/en/Glob_(programming)) can be used.
# Do mind that double stars are reserved in yaml
# these should be escaped with a: \ or the name should be in double quotes e.g. "HARDWARE_DRIVER*.c"
sourceFiles:
  - startup_stm32f469xx.s
  - Core/Src/main.c
  - Core/Src/gpio.c
  - Core/Src/crc.c
  - Core/Src/dma2d.c
  - Core/Src/dsihost.c
  - Core/Src/fmc.c
  - Core/Src/i2c.c
  - Core/Src/ltdc.c
  - Core/Src/quadspi.c
  - Core/Src/sai.c
  - Core/Src/sdio.c
  - Core/Src/tim.c
  - Core/Src/usart.c
  - Core/Src/stm32f4xx_it.c
  - Core/Src/stm32f4xx_hal_msp.c
  - Core/Src/stm32f4xx_hal_timebase_tim.c
  - USB_HOST/Target/usbh_conf.c
  - USB_HOST/Target/usbh_platform.c
  - USB_HOST/App/usb_host.c
  - FATFS/App/fatfs.c
  - FATFS/Target/bsp_driver_sd.c
  - FATFS/Target/sd_diskio.c
  - FATFS/Target/fatfs_platform.c
  - PDM2PCM/App/pdm2pcm.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma2d.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dsi.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fmc.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sdram.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc_ex.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_qspi.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sai.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sai_ex.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c
  - Core/Src/system_stm32f4xx.c
  - Middlewares/Third_Party/FatFs/src/diskio.c
  - Middlewares/Third_Party/FatFs/src/ff.c
  - Middlewares/Third_Party/FatFs/src/ff_gen_drv.c
  - Middlewares/Third_Party/FatFs/src/option/syscall.c
  - Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_core.c
  - Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_ctlreq.c
  - Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_ioreq.c
  - Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_pipes.c
  - Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Src/usbh_cdc.c
  - Src/**
  - Core/Src/**
  - Core/Lib/**

# When no makefile is present it will show a warning pop-up.
# However when compilation without the CubeMX Makefile is desired, this can be turned of.
suppressMakefileWarning: false
